export const CUSTOMER_THEMES = [
  {
    id: "sunset",
    name: "Sunset Orange",
    color: "#ff5722",
    description: "Warm diner look with a stark dark headers and vibrant orange accent colors. Highly engaging.",
    classes: {
      wrapper: "bg-slate-50 text-slate-800 min-h-screen",
      headerBanner: "bg-slate-950 text-white",
      accentBadge: "bg-white/10 text-white border border-white/10",
      accentText: "text-[#ff5722]",
      accentBtn: "bg-[#ff5722] text-white hover:bg-[#e04c1c] focus:ring-[#ff5722]/20",
      cardBg: "bg-white border border-slate-150 shadow-sm shadow-slate-100/30",
      inputBg: "bg-white text-slate-850 border-slate-200 focus:border-[#ff5722]/50 focus:ring-[#ff5722]/20 placeholder:text-slate-400",
      pillInactive: "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50",
      pillActive: "bg-slate-950 border border-slate-950 text-white shadow-md",
      footerCart: "bg-white/95 border-t border-slate-200 text-slate-800 shadow-2xl",
      itemCardTitle: "text-slate-900",
      itemCardPrice: "text-[#ff5722]",
      headerAccentText: "text-[#ff5722]"
    },
    loader: {
      bgClass: "min-h-screen bg-slate-955 text-white flex flex-col justify-center items-center p-6 text-center space-y-8 relative overflow-hidden select-none",
      glowRingClass: "absolute -right-32 -top-32 w-64 h-64 bg-[#ff5722]/15 rounded-full blur-3xl pointer-events-none animate-glow-ring",
      glowRingClassLeft: "absolute -left-32 -bottom-32 w-64 h-64 bg-slate-900/30 rounded-full blur-3xl pointer-events-none",
      floatingLeaves: null,
      spinnerContainerClass: "w-24 h-24 rounded-full border border-white/5 bg-slate-900/80 flex items-center justify-center p-1.5 shadow-[0_0_40px_rgba(255,87,34,0.2)]",
      spinnerClass: "w-full h-full rounded-full border-2 border-dashed border-[#ff5722] animate-spin flex items-center justify-center",
      icon: "🧑‍🍳",
      iconClass: "absolute text-4xl animate-bounce",
      badgeText: "🔥 Hot & Fresh",
      badgeClass: "px-3 py-1 bg-[#ff5722]/10 border border-[#ff5722]/20 text-[#ff5722] rounded-full text-[9px] font-black uppercase tracking-widest",
      titleText: (name) => `🧑‍🍳 ${name}`,
      titleClass: "text-2xl font-black tracking-tight text-white max-w-xs mx-auto leading-tight animate-pulse",
      subtitleText: "Loading Fresh Meals...",
      subtitleClass: "text-sm font-bold text-orange-400 uppercase tracking-widest mt-1",
      footerText: "Connecting Live Kitchen Feed...",
      footerClass: "flex items-center gap-1.5 text-slate-500 text-[9px] font-black uppercase tracking-widest mt-8",
      footerDotColor: "bg-[#ff5722] animate-ping"
    },
    welcome: {
      bgClass: "min-h-screen bg-slate-950 text-white flex flex-col justify-between p-6 select-none relative overflow-hidden font-sans",
      glowRingClass: "absolute -right-32 -top-32 w-64 h-64 bg-[#ff5722]/10 rounded-full blur-3xl pointer-events-none animate-glow-ring",
      glowRingClassLeft: "absolute -left-32 -bottom-32 w-64 h-64 bg-slate-900/30 rounded-full blur-3xl pointer-events-none",
      floatingLeaves: null,
      badgeText: (greet) => greet,
      badgeClass: "px-3 py-1 bg-[#ff5722]/15 border border-[#ff5722]/20 text-[#ff5722] rounded-full text-[9px] font-black uppercase tracking-widest",
      welcomeText: "Welcome to",
      welcomeClass: "text-3xl font-black tracking-tight text-white mt-3 leading-none",
      restaurantNameClass: "text-2xl font-black text-orange-500 mt-1",
      cardClass: "my-auto max-w-sm mx-auto w-full bg-slate-900/80 border border-slate-800/80 p-6 rounded-[2.5rem] shadow-[0_0_50px_rgba(255,87,34,0.06)] text-center space-y-6 animate-fade-in-up",
      iconClass: "w-16 h-16 bg-slate-900 border border-slate-800 rounded-full flex items-center justify-center text-3xl mx-auto shadow-2xl",
      icon: "🧑‍🍳",
      tableLabelClass: "text-slate-400 text-xs font-semibold",
      tableBadgeClass: "inline-flex items-center gap-2 px-5 py-2 bg-[#ff5722]/10 border border-[#ff5722]/35 rounded-full text-[#ff5722] font-black text-sm uppercase shadow-sm",
      bulletContainerClass: "border-t border-slate-850 pt-4 space-y-3.5 text-left text-xs font-bold text-slate-350",
      bulletIconColor: "text-[#ff5722]",
      bullets: [
        { icon: "⚡", text: "Instant Table Order Dispatch" },
        { icon: "🍳", text: "Live KOT Cooking Feed" },
        { icon: "🛎️", text: "Call Waiter & Check Billing" }
      ],
      buttonClass: "w-full max-w-xs mx-auto py-4 bg-[#ff5722] hover:bg-[#e04c1c] text-white font-black text-xs tracking-widest uppercase rounded-2xl shadow-xl shadow-orange-500/10 transition active:scale-95 duration-200 cursor-pointer",
      footerText: "RESTUVEXO SMART DINER SYSTEM"
    }
  },
  {
    id: "midnight",
    name: "Midnight Luxury",
    color: "#f59e0b",
    description: "Deep charcoal slate backgrounds with warm gold triggers. Extremely premium look.",
    classes: {
      wrapper: "bg-slate-955 text-white min-h-screen",
      headerBanner: "bg-slate-900 border-b border-slate-800 text-white",
      accentBadge: "bg-amber-500/10 text-amber-400 border border-amber-500/20",
      accentText: "text-amber-400",
      accentBtn: "bg-amber-500 text-slate-950 hover:bg-amber-600 focus:ring-amber-500/20",
      cardBg: "bg-slate-900/90 border border-slate-850/80 shadow-2xl shadow-slate-950/20",
      inputBg: "bg-slate-900 text-white border-slate-850 focus:border-amber-500/50 focus:ring-amber-500/20 placeholder:text-slate-600",
      pillInactive: "bg-slate-900/60 border border-slate-850 text-slate-400 hover:text-white",
      pillActive: "bg-amber-500 border border-amber-500 text-slate-955 shadow-lg shadow-amber-500/10",
      footerCart: "bg-slate-900/95 border-t border-slate-800 text-white",
      itemCardTitle: "text-white",
      itemCardPrice: "text-amber-400",
      headerAccentText: "text-amber-400"
    },
    loader: {
      bgClass: "min-h-screen bg-black text-white flex flex-col justify-center items-center p-6 text-center space-y-8 relative overflow-hidden select-none",
      glowRingClass: "absolute -right-32 -top-32 w-64 h-64 bg-amber-500/15 rounded-full blur-3xl pointer-events-none animate-glow-ring",
      glowRingClassLeft: "absolute -left-32 -bottom-32 w-64 h-64 bg-slate-900/40 rounded-full blur-3xl pointer-events-none",
      floatingLeaves: null,
      spinnerContainerClass: "relative flex items-center justify-center w-24 h-24 rounded-full border border-amber-500/20 flex items-center justify-center p-1.5 shadow-[0_0_40px_rgba(245,158,11,0.15)]",
      spinnerClass: "w-full h-full rounded-full border border-dashed border-amber-500/40 animate-spin-slow flex items-center justify-center",
      icon: "🧑‍🍳",
      iconClass: "absolute text-4xl animate-pulse",
      badgeText: "✨ RESTUVEXO Signature Dining",
      badgeClass: "px-3 py-1 bg-amber-500/10 border border-amber-500/20 text-amber-400 rounded-full text-[9px] font-black uppercase tracking-widest animate-pulse",
      titleText: (name) => `Welcome to ${name} Signature Dining`,
      titleClass: "text-xl font-light tracking-widest text-slate-100 max-w-xs mx-auto leading-relaxed",
      subtitleText: null,
      subtitleClass: "",
      footerText: "Establishing secure terminal...",
      footerClass: "flex items-center gap-1.5 text-slate-500 text-[9px] font-black uppercase tracking-widest mt-8",
      footerDotColor: "bg-amber-500 animate-ping"
    },
    welcome: {
      bgClass: "min-h-screen bg-slate-950 text-white flex flex-col justify-between p-6 select-none relative overflow-hidden font-sans",
      glowRingClass: "absolute -right-32 -top-32 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none animate-glow-ring",
      glowRingClassLeft: "absolute -left-32 -bottom-32 w-64 h-64 bg-slate-900/40 rounded-full blur-3xl pointer-events-none",
      floatingLeaves: null,
      badgeText: (greet) => greet,
      badgeClass: "px-3 py-1 bg-amber-500/10 border border-amber-500/20 text-amber-400 rounded-full text-[9px] font-black uppercase tracking-widest",
      welcomeText: "Welcome to",
      welcomeClass: "text-3xl font-light tracking-wide text-white mt-3 font-serif",
      restaurantNameClass: "text-2xl font-extrabold tracking-tight text-amber-400 font-serif",
      cardClass: "my-auto max-w-sm mx-auto w-full backdrop-blur-2xl bg-slate-900/60 border border-slate-800/80 p-6 rounded-[2.5rem] shadow-[0_0_50px_rgba(245,158,11,0.05)] text-center space-y-6 animate-fade-in-up",
      iconClass: "w-16 h-16 bg-slate-900 border border-slate-800 rounded-full flex items-center justify-center text-3xl mx-auto shadow-2xl",
      icon: "🛎️",
      tableLabelClass: "text-slate-400 text-xs font-semibold",
      tableBadgeClass: "inline-flex items-center gap-2 px-5 py-2 bg-amber-500/10 border border-amber-500/35 rounded-full text-amber-400 font-black text-sm uppercase shadow-sm",
      bulletContainerClass: "border-t border-slate-850 pt-4 space-y-3.5 text-left text-xs font-bold text-slate-350",
      bulletIconColor: "text-amber-400",
      bullets: [
        { icon: "📱", text: "Interactive Self-Ordering Portal" },
        { icon: "🍳", text: "Live KOT Preparation Tracker" },
        { icon: "🍽️", text: "Contactless & Seamless Service" }
      ],
      buttonClass: "w-full max-w-xs mx-auto py-4 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-black text-xs tracking-widest uppercase rounded-2xl shadow-xl shadow-amber-500/10 transition active:scale-95 duration-200 cursor-pointer",
      footerText: "RESTUVEXO signature system"
    }
  },
  {
    id: "emerald",
    name: "Emerald Bistro",
    color: "#10b981",
    description: "Organic mint green theme with fresh, soft cream details. Calm organic cafe vibes.",
    classes: {
      wrapper: "bg-[#f4f7f1] text-slate-800 min-h-screen",
      headerBanner: "bg-[#10b981] text-white",
      accentBadge: "bg-[#ecfbf5] text-[#10b981] border border-[#a7f3d0]",
      accentText: "text-[#10b981]",
      accentBtn: "bg-[#10b981] text-white hover:bg-emerald-600 focus:ring-[#10b981]/20",
      cardBg: "bg-white border border-[#edf3e8] shadow-md shadow-slate-100/40",
      inputBg: "bg-white text-slate-850 border-[#d2dfc3] focus:border-[#10b981]/50 focus:ring-[#10b981]/20 placeholder:text-slate-400",
      pillInactive: "bg-white border border-[#dce6d2] text-slate-600 hover:bg-[#f6f9f3]",
      pillActive: "bg-[#10b981] border border-[#10b981] text-white shadow-lg shadow-emerald-500/10",
      footerCart: "bg-white/95 border-t border-[#edf3e8] text-slate-850 shadow-2xl",
      itemCardTitle: "text-slate-900",
      itemCardPrice: "text-emerald-600",
      headerAccentText: "text-emerald-100"
    },
    loader: {
      bgClass: "min-h-screen bg-[#f4f7f1] text-slate-800 flex flex-col justify-center items-center p-6 text-center space-y-8 relative overflow-hidden select-none",
      glowRingClass: null,
      glowRingClassLeft: null,
      floatingLeaves: [
        { text: "🌿", animation: "animate-float-leaf-1", style: { right: -16, top: -16 } },
        { text: "🍃", animation: "animate-float-leaf-2", style: { left: -16, bottom: -16 } },
        { text: "🍀", animation: "animate-float-leaf-3", style: { right: 12, bottom: 20 } }
      ],
      spinnerContainerClass: "relative flex items-center justify-center w-24 h-24 rounded-full bg-emerald-500/5 flex items-center justify-center",
      spinnerClass: "w-20 h-20 rounded-full border-2 border-emerald-500/10 border-t-emerald-500 animate-spin",
      icon: "🥗",
      iconClass: "absolute text-4xl animate-bounce",
      badgeText: "🌿 Farm-To-Table Dining",
      badgeClass: "px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 rounded-full text-[9px] font-black uppercase tracking-widest",
      titleText: (name) => `🌿 Preparing Your Dining Experience`,
      titleClass: "text-xl font-black tracking-tight text-slate-800 max-w-xs mx-auto leading-tight",
      subtitleText: (name) => name,
      subtitleClass: "text-[10px] text-slate-400 font-bold uppercase tracking-wide",
      footerText: "Syncing Fresh Menu...",
      footerClass: "flex items-center gap-1.5 text-emerald-600/70 text-[9px] font-black uppercase tracking-widest mt-8",
      footerDotColor: "bg-emerald-500 animate-pulse"
    },
    welcome: {
      bgClass: "min-h-screen bg-[#f4f7f1] text-slate-800 flex flex-col justify-between p-6 select-none relative overflow-hidden font-sans",
      glowRingClass: null,
      glowRingClassLeft: null,
      floatingLeaves: [
        { text: "🌿", animation: "animate-float-leaf-1", style: { right: -16, top: -16 } },
        { text: "🍃", animation: "animate-float-leaf-2", style: { left: -16, bottom: -16 } }
      ],
      badgeText: (greet) => greet,
      badgeClass: "px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-700 rounded-full text-[9px] font-black uppercase tracking-widest",
      welcomeText: "Welcome to",
      welcomeClass: "text-3xl font-black tracking-tight text-slate-900 mt-3 leading-none",
      restaurantNameClass: "text-2xl font-black text-emerald-700 mt-1",
      cardClass: "my-auto max-w-sm mx-auto w-full bg-white border border-[#edf3e8] p-6 rounded-[2.5rem] shadow-[0_20px_45px_rgba(16,185,129,0.06)] text-center space-y-6 animate-fade-in-up",
      iconClass: "w-16 h-16 bg-[#ecfbf5] border border-[#a7f3d0] rounded-full flex items-center justify-center text-3xl mx-auto shadow-sm",
      icon: "🥗",
      tableLabelClass: "text-slate-500 text-xs font-bold",
      tableBadgeClass: "inline-flex items-center gap-2 px-5 py-2 bg-emerald-500/10 border border-emerald-500/25 rounded-full text-emerald-700 font-black text-sm uppercase shadow-sm",
      bulletContainerClass: "border-[#edf3e8] pt-4 space-y-3.5 text-left text-xs font-bold text-slate-600",
      bulletIconColor: "text-emerald-500",
      bullets: [
        { icon: "📱", text: "Fresh Interactive Menu & Orders" },
        { icon: "🍳", text: "Kitchen Cooking Process Radar" },
        { icon: "🌱", text: "Clean Ingredients, Served Hot" }
      ],
      buttonClass: "w-full max-w-xs mx-auto py-4 bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs tracking-widest uppercase rounded-2xl shadow-xl shadow-[#10b981]/10 transition active:scale-95 duration-200 cursor-pointer",
      footerText: "RESTUVEXO Organic Diner System"
    }
  }
];
